[package]
name = "keycrab_crypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
ed25519-dalek = "1.0.1"
gpgme = "0.11.0"
